version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/mysql-init:/docker-entrypoint-initdb.d # Diretório para scripts de inicialização do MySQL
    networks:
      - nestjs_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db
      - ./database/mongo-init:/docker-entrypoint-initdb.d # Diretório para scripts de inicialização do MongoDB
    networks:
      - nestjs_network

volumes:
  mysql-data:
  mongo-data:

networks:
  nestjs_network:
